---
title: "Trade War and Trump's Approval Rate"
author: "Haokun Zhang and Abby Johnson"
date: "5/13/2022"
output: pdf_document
---

```{r setup, include=FALSE}
#import modules
library(dplyr)
library(ggplot2)
library(rdrobust)
library(magrittr)
library(haven)
library(tidyverse)
library(data.table)
library(fixest)
library(glue)
library(data.table)
library(caret)
library(glmnet)
library(gbm)
library(ggmap)
library(rpart)
library(rpart.plot)
library(randomForest)
library(rsample)
library(modelr)
library(fastDummies)
library(scales)
library(here)
library(knitr)
library(kableExtra)
library(stargazer)
library(here)
library(foreach)
library(rddensity)
library(dplyr)
library(modelsummary)

path <- here()
```

## R Markdown


```{r data_descripton, echo = FALSE}
#import data
trump_vote = read.csv("C:/Users/Haokun Zhang/Desktop/github/trade_war_effects/data/approval_topline.csv")

#filter the data to only voters
voter_data = trump_vote %>%
  filter(subgroup == "Voters")
voter_data = voter_data %>%
  select(subgroup, 
         modeldate, 
         approve_estimate, 
         approve_hi, 
         approve_lo, 
         disapprove_estimate, 
         disapprove_hi, 
         disapprove_lo) 

# create a dataframe of voter_data
df_voter_data <- data.frame(modeldate = c(voter_data$modeldate), 
                            approve_estimate = c(voter_data$approve_estimate))

# describing modeldate in date class
df_voter_data$modeldate <- as.Date(voter_data$modeldate, format = "%m/%d/%Y")

# plot of distribution across time with both cutoff dates
p <- ggplot(data = df_voter_data, aes(x=modeldate, y=approve_estimate)) + geom_line() + scale_x_date(date_labels = "%Y/%m/%d") + geom_vline(xintercept = as.Date("2018-04-02"), color = "red")

# show p
plot(p)

p2 <- ggplot(data = df_voter_data, aes(x=modeldate, y=approve_estimate)) + geom_line() + scale_x_date(date_labels = "%Y/%m/%d") + geom_vline(xintercept = as.Date("2018-06-15"), color = "red")
plot(p2)
```

```{r "local_linear_RD_point_estimator_with h=20_and_uniform_kernel", echo=FALSE}
cutoff = as.integer(as.Date("2018-04-02"))

out1 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "uniform", p =1, h = 20, c= cutoff)
summary(out1)

#statistically insignificant results
#arbitrary bandwidth

```

```{r local linear RD point estimator with h=20 and triangular kernel, echo=FALSE}
out2 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, h = 20, c= cutoff)
summary(out2)

#statistically insignificant results
#arbitrary bandwidth

```

```{r local quadratic RD with triangular kernel, h=20 and p=2, echo=FALSE}
out3 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =2, h = 20, c= cutoff)
summary(out3)

#arbitrary bandwidth

```

```{r "optimal bandwidth selection using MSE-optimal bandwidth", echo=FALSE}
bwd1 = rdbwselect(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "mserd", c= cutoff)
summary(bwd1)
```

```{r "optimal bandwidth selection using two MSE-optimal", echo=FALSE}
bwd2 = rdbwselect(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "msetwo" , c= cutoff)
summary(bwd2)
```


```{r "local linear RD with MSE bandwidth", echo=FALSE}
m1 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "mserd", c= cutoff, all=TRUE)
summary(out4)
```

```{r local linear RD with triangular kernel and exlcuded regularization term}
m2 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =2, bwselect = "mserd", c= cutoff, all = TRUE)
summary(out5)
```

```{r local linear RD with triangular kernel with all is TRUE}
m3 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =2, bwselect = "mserd", all=TRUE, c= cutoff)
summary(out6)
```

```{r "local linear RD with triangular kernel with CER-optimal bandwith choice", echo=FALSE}
out7 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "cerrd", c= cutoff)
summary(out7)

#statistically insignificant results
```

```{r "all bandwidth", echo=FALSE}
bdw3 = rdbwselect(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, all = TRUE, c= cutoff)
summary(bdw3)

# shows all bandwidth calculations
```


```{r out8 with covariates, echo=FALSE}

Z = cbind(voter_data$approve_hi, voter_data$approve_lo, voter_data$disapprove_estimate,
voter_data$disapprove_hi, voter_data$disapprove_lo)

df_voter_data = df_voter_data %>%
  mutate(approve_hi = Z[,1], approve_lo = Z[,2], disapprove_estimate = Z[,3], disapprove_hi = Z[,4], disapprove_lo = Z[,5])

cov = cbind(df_voter_data$approve_hi, df_voter_data$approve_lo, df_voter_data$disapprove_estimate,
df_voter_data$disapprove_hi, df_voter_data$disapprove_lo)

y = (df_voter_data$approve_estimate)
x = as.integer(df_voter_data$modeldate)
c= as.integer(as.Date("2018-04-2"))

out8 = rdrobust(y, x, c= c, covs = cov, kernel = "triangular", scaleregul = 1,p = 1, bwselect = "mserd", all = TRUE)
summary(out8)

```

```{r cutoff1 models table, echo=FALSE}
tidy.rdrobust <- function(model, ...) {
  ret <- data.frame(
    term = row.names(model$coef),
    estimate = model$coef[, 1],
    std.error = model$se[, 1],
    p.value = model$pv[, 1]
  )
  row.names(ret) <- NULL
  ret
}

glance.rdrobust <- function(model, ...) {
  ret <- data.frame(
    Kernel = model$kernel,
    Bandwidth = model$bwselect
  )
  ret
}

models <- list(m1, m2, m3)

modelsummary(models, statistic = "std.error", stars=TRUE, title = "RD Estimates for Approval Rate after U.S. Tariffs")

```


```{r rdplot, echo=FALSE}

## Implement rdplot 
y = (df_voter_data$approve_estimate)
x = as.integer(df_voter_data$modeldate)
c= as.integer(as.Date("2018-04-2"))

rdplot(y, x, c=c, p=1, binselect="es", 
       title="RD Plot: Trump Approval Rate over Time", 
       y.label="Approval Estimate",
       x.label="Date (as integer)")

rdplot(y, x, c=c, p=2, binselect="es", 
       title="RD Plot: Trump Approval Rate over Time", 
       y.label="Approval Estimate",
       x.label="Date (as integer)")

rdplot(y, x, c=c, p=3, binselect="es", 
       title="RD Plot: Trump Approval Rate over Time", 
       y.label="Approval Estimate",
       x.label="Date (as integer)")
```
```{r cutoff2 models, echo=FALSE}
cutoff = as.integer(as.Date("2018-06-15"))

out1 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "uniform", p =1, h = 20, c= cutoff)
summary(out1)

out2 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, h = 20, c= cutoff)
summary(out2)

out3 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =2, h = 20, c= cutoff)
summary(out3)

out4 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "mserd", c= cutoff, all = TRUE)
summary(out4)

out5 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", scaleregul = 0, p =1, bwselect = "mserd", c= cutoff, all = TRUE)
summary(out5)

out6 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =2, bwselect = "mserd", all=TRUE, c= cutoff)
summary(out6)

out7 = rdrobust(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "cerrd", c= cutoff)
summary(out7)

bwd1 = rdbwselect(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "mserd", c= cutoff)
summary(bwd1)

bwd2 = rdbwselect(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, bwselect = "msetwo" , c= cutoff)
summary(bwd2)

bdw3 = rdbwselect(df_voter_data$approve_estimate, df_voter_data$modeldate, kernel = "triangular", p =1, all = TRUE, c= cutoff)
summary(bdw3)

c= as.integer(as.Date("2018-06-15"))

out8 = rdrobust(y, x, c= c, covs = cov, kernel = "triangular", scaleregul = 1,p = 1, bwselect = "mserd")
summary(out8)
```

```{r cutoff2 models table, echo=FALSE}

tidy.rdrobust <- function(model, ...) {
  ret <- data.frame(
    term = row.names(model$coef),
    estimate = model$coef[, 1],
    std.error = model$se[, 1],
    p.value = model$pv[, 1]
  )
  row.names(ret) <- NULL
  ret
}

glance.rdrobust <- function(model, ...) {
  ret <- data.frame(
    Kernel = model$kernel,
    Bandwidth = model$bwselect
  )
  ret
}

models <- list(out4, out5, out6)

modelsummary(models, statistic = "std.error", stars=TRUE, title = "RD Estimates for Approval Rate after China Tariffs")

```

```{r cutoff2 rdplot, echo=FALSE}
y = (df_voter_data$approve_estimate)
x = as.integer(df_voter_data$modeldate)
c= as.integer(as.Date("2018-06-15"))

rdplot(y, x, c=c, p=1, binselect="es", 
       title="RD Plot: Trump Approval Rate over Time", 
       y.label="Approval Estimate",
       x.label="Date (as integer)")

rdplot(y, x, c=c, p=2, binselect="es", 
       title="RD Plot: Trump Approval Rate over Time", 
       y.label="Approval Estimate",
       x.label="Date (as integer)")

rdplot(y, x, c=c, p=3, binselect="es", 
       title="RD Plot: Trump Approval Rate over Time", 
       y.label="Approval Estimate",
       x.label="Date (as integer)")
```



```{r rddensity and rddensity plot, echo=FALSE}
rdd = rddensity(X = df_voter_data$modeldate, c= as.integer(as.Date("2018-04-02")), bwselect = "each", p=1, all = TRUE, kernel = "triangular")

rdplot <- rdplotdensity(rdd, X = df_voter_data$modeldate)


rdd = rddensity(X = df_voter_data$modeldate, c= as.integer(as.Date("2018-06-15")), bwselect = "each", p=1, all = TRUE, kernel = "triangular")

rdplot <- rdplotdensity(rdd, X = df_voter_data$modeldate)

```


